NIT-Administrative-Systems/AS-CloudDocs

.vuepress/config.js
github/settings-permissions.md

Adds an article on our github teams & permissions.

Add github policies

---

.vuepress/config.js
README.md
roles-responsibilities.md
tools.md

This PR adds a RACI that divvies up cloud operation tasks between PIPS-CloudOps, EACD-CloudOps, leads, and devs.
- I tried to keep it small (e.g. TNS has one role but PIPS-CloudOps interfaces w/ them for it so it's not on here cuz AS don't care), with just common items. I don't want it to be like 50 lines cuz then people's eyes will just glaze over...
@cecolby11 @bab4379 thoughts on the RACI?
There's a list of recommended tools and some VS Code plugins too. Should anything else be on there?

RACI & tool recommendations

---

.vuepress/config.js
github/policies.md

Adds some policies for secrets in repos & github marketplace integrations.

Secret & integration policies for github

---

iac/available-modules.md
iac/state-buckets.md

Listings for the IaC modules we've made available & the account state buckets.

Listings for IaC modules & buckets

---

.vuepress/config.js
infrastructure/alb.md
infrastructure/vpc-ip-addr.md

This PR fills out the IP subnet allocation article and adds notes on the shared ALB.

Common resources

---

tools.md

Add some marketing for EACD's BrowserStack subscription.

Add notes for BrowserStack

---

.vuepress/config.js
infrastructure/vapor.md

Intro to vapor, notes on limitations, and a Jenkinsfile that deals with the split-team stuff for nonprod vs. prod.

Using Vapor for infrastructure

---

infrastructure/certificates.md

- Fixes the tf link (datasource -> resource)
- Notes on the entapp zone

Certificate validation fixes

---

.vuepress/config.js
design-for-cloud.md

Add a page (which is really kind of a stub) about app architecture for the cloud.

App Architecture for the Cloud

---

README.md

Intro page now looks like it was written by a human :P

First stab at an intro page

---

.vuepress/config.js
iac/terraform-concepts.md
iac/tf-upgrading.md

Adds a Terraform upgrade guide for AS.

Terraform upgrade guide

---

.vuepress/config.js

Adds a favicon

---

ci-cd/jenkins.md

Note on how Jenkins needs @awsCloudOpsCJT to be a collaborator for stuff to work.

Notes on Jenkins accessing github

---

.vuepress/config.js
github/repo-layout.md

Adds some GH repo layout standards for Jenkins, the Github stuff, and Dependabot.
Is there anything else this should include?

Repository layout recommendations

---

iac/tf-upgrading.md

- Note about the warnings the upgrade command leaves us
- Running a tf plan in dev
- Adding auto-approve to apply

TF upgrade guide refinements

---

iac/terraform-concepts.md

Declaration that IaC is the one true way.

Statement that IAC is the way

---

.vuepress/config.js
iac/faq.md
infrastructure/api-gateway.md

This adds a doc about API Gateway & how we recommend using it.
I also added some TF FAQ items.
Looking for ideas for more!

FAQ & API Gateway doc

---

.vuepress/config.js
.vuepress/public/gh-workflow.html
.vuepress/public/git-branching-from-dev-problem.html
github/workflow.md

This is a brief doc (intentionally vague) on our GH workflow.

Github workflow

---

github/policies.md
github/workflow.md

- Secrets can't be removed from github
- FIx URLs for my diagrams, they don't work on the github.io site right now :(

GitHub doc - minor fixes

---

.vuepress/config.js
infrastructure/iam.md
infrastructure/lambda.md
infrastructure/vpc-ip-addr.md

- Lambda best practices for the CloudWatch thing
- General guidence on writing IAM policies
- Considerations for IP subnet assignment

Lambda & IAM recommendations

---

iac/state-buckets.md

Building out the reference material.

Add details on shared account resource tfstate S3 keys

---

.vuepress/config.js
infrastructure/tagging.md

Document our two standard tags & easiest way to achieve that with TF.

Tagging standard

---

.vuepress/config.js
infrastructure/databases.md

Dynamo & RDS

---

.vuepress/config.js
infrastructure/ses.md

This covers what SES is (and is NOT), stuff about policies, and an inventory of SES setup status across our accounts.

Article about SES usage

---

.vuepress/config.js
infrastructure/alerts.md

Links to CW docs & has an example for sending to OpsGenie.

Basic CW stuff w/ SNS & OpsGenie

---

yarn.lock

Bumps all the deps & deps-of-deps, to clear the security alert.

Dependency bump

---

infrastructure/iam.md
infrastructure/secrets.md

This documents:
- Developer roles and their permissions
- How to use KMS w/ parameters
- How to view your encrypted secrets in the console without oversharing

Viewing your own secrets

---

.vuepress/config.js

@jem3523 pointed out the edit links don't work -- fixing that 😀

Fix the branch/docs dir so the edit buttons VuePress provide work

---

iac/terraform-concepts.md
yarn.lock

Further utility documentation was added to the terraform-concepts.md file so that users can configure multiple profiles, as well as set up a standard function to shorten the log-in process.
- [x ] Proof-reading
- [ no diagrams included] Any diagrams/figures have their source files included

Added further utility documentation to the terraform-concepts.md file

---

development/libraries.md

Wrote this lib last month; adding a link to make it more discoverable.

Add link to NU Laravel UI lib

---

github/repo-layout.md

Updates the dependabot notes for Dependabot v2.

Update dependabot info in github repo layout doc

---

yarn.lock

Bump dependencies to try and fix build

---

development/app-patterns.md
development/libraries.md
infrastructure/api-gateway.md

Some words on API Gateway & our nodeJS microservice app template.

Nodejs app pattern

---

iac/available-modules.md

Add fargate task to list of available shared AS modules.

add fargate task to available modules

---

.vuepress/config.js
infrastructure/fargate.md

Add general documentation about Fargate terms/concepts.

add documentation about fargate tasks and services

---

.gitignore
iac/available-modules.md
infrastructure/fargate.md

- Adds documentation for app autoscaling scheduled scaling with ECS 
- Adds fargate service module to available modules 
- Polishes the existing fargate documentation

Add documentation for using scheduled scaling

---

.vuepress/config.js
iac/tf-move.md

Document terraform state move procedure and example use case after successfully testing the operation on fc-infra s3 buckets.

add documentation about terraform state move

---

infrastructure/vapor.md

This PR to add the step to check the team before running the vapor cert command

adding the step to check vapor cli team

---

package.json
yarn.lock

Easier than merging all those PRs

Bumps dep versions

---

iac/available-modules.md

I think this is the only fix we can do.
There's a couple `master` and `slave` references, but they're in links or commands where they can't be changed.
https://www.it.northwestern.edu/about/it-projects/dei/glossary.html

Fix up language based on IT DEI glossary

---

.vuepress/config.js
development/app-patterns.md
development/express-stack.md
development/frontend-stacks.md
development/laravel-stack.md
development/libraries.md
development/spring-stack.md

Moses asked if we could add a list of recommended libs/tools, so here's a first stab at that.
1. Let me know if you think anything here is UNSUITABLE for inclusion (take-backs are hard)
1. Feel free to suggest (or just directly add) any other libs for inclusion

Add big ol' list of recommended libraries

---

docs-site.md

Private github pages

---

.vuepress/config.js
security/sso-approaches.md

Outline of SSO methods

---

security/sso-approaches.md

Link to the graph API docs instead of vaguely hinting at them.

Clarify this paragraph

---

ci-cd/gha.md

This PR includes my journal about my experiences learning GitHub Actions.  
It is a first step in sharing:
- High-level information about GitHub Actions
- Suggested learning approach
- Resources
- Tips and Tricks
within Admin Systems.

GitHub actions

---

.vuepress/config.js
ci-cd/gha.md

After this was built my page did not show in the side nav, but I can navigate to it directly.  I think I need a top-level header maybe?
Header so it shows up on the site's navigation

Adding a high-level header

---

ci-cd/gha.md

Adds a new section to highlight reusable workflows and custom actions created by NUIT

Adding gha reusable wf doc

---

.vuepress/config.ts
infrastructure/file-handling-on-lambda.md

This already incorporates the changes from the PR to the EACD site.

Serverless File Uploads with S3

---

infrastructure/vapor.md

Adding some personal notes from lessons-learned with creating a new vapor environment for SOAP

Adding vapor notes
